# SwiftLint Configuration for Ariadne

# Paths to include/exclude
included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - Package.swift
  - .git

# Rules Configuration
opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - switch_case_alignment
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call

disabled_rules:
  - todo
  - line_length # Handled by custom rule
  - type_body_length # Handled by custom rule

# Custom Rule Configuration
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 100
  error: 150

file_length:
  warning: 500
  error: 1000

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

identifier_name:
  min_length: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - ip
    - os
    - x
    - y

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 5
  function_level:
    warning: 5
    error: 10

# Force unwrapping configuration
force_unwrapping:
  severity: warning

# Force try configuration
force_try:
  severity: warning

# Custom rules
custom_rules:
  comments_space:
    name: "Space After Comment"
    regex: "(^ *//\\w+)"
    message: "There should be a space after //"
    severity: warning
    
  comments_capitalization:
    name: "Capitalize Comments"
    regex: "(^ *// +\\w)"
    message: "Comments should be capitalized"
    severity: warning
    
  empty_line_after_guard:
    name: "Empty Line After Guard"
    regex: "(guard\\s+.*\\}\\s*(?!\\s*\\n))"
    message: "There should be an empty line after a guard"
    severity: warning
    
  empty_line_after_super:
    name: "Empty Line After Super"
    regex: "(super\\.\\w+\\(.*\\)\\s*(?!\\s*\\n))"
    message: "There should be an empty line after calling super"
    severity: warning

# Reporter configuration
reporter: "xcode"

# Analyzer rules (for deeper analysis)
analyzer_rules:
  - unused_import
  - unused_declaration